---
name: galaxy

"on":
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  galaxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Galaxy upload
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_TOKEN }}

...
